# pyproject.toml
# ------------------------------------------------------------
# Build system – tells pip how to build the package
# ------------------------------------------------------------
[build-system]
requires = ["setuptools>=61.0,<80", "wheel"]   # “wheel” is optional but speeds up install
build-backend = "setuptools.build_meta"

# ------------------------------------------------------------
# Project metadata (PEP‑621 style)
# ------------------------------------------------------------
[project]
name = "operadar"
version = "1.0.1"
description = "Radar forward operator developed at the National Centre for Meteorological Research, France"
requires-python = ">=3.10"

# Authors – you can list multiple authors if needed
authors = [
    {name = "C. Augros"},
    {name = "C. David"},
]

# Runtime dependencies
# Installed with pip install -e .
dependencies = [
    "pyproj",
    "numpy",
    "xarray>=2023.2",
    "pandas",
    "netCDF4",
    "dask>=2023.2",
    "scipy",
    "tqdm>=4.65",
    "pyyaml",
    "matplotlib>=3.6",
    "cartopy>=0.21",
    "contourpy",
    "epygram",
    "h5py",
]

# Runtime dependencies with fixed package version for belenos
# Installed with pip install -e ".[belenos]"
[project.optional-dependencies]
belenos = [
    "pyproj==3.7.1",
    "numpy==2.2.6",
    "xarray==2025.12.0",
    "pandas==2.3.2",
    "netCDF4==1.7.2",
    "dask==2026.3.0",
    "scipy==1.15.3",
    "tqdm==4.67.3",
    "pyyaml==6.0.3",
    "matplotlib==3.9.0",
    "cartopy==0.24.1",
    "contourpy==1.3.2",
    "epygram==2.0.7",
    "h5py==3.14.0",     
]


# URL for the home‑page / source repository
[project.urls]
Homepage = "https://github.com/UMR-CNRM/operadar.git"

# ------------------------------------------------------------
# Setup‑tools specific configuration
# ------------------------------------------------------------
[tool.setuptools]
# This flag makes setuptools also pull in the files listed in MANIFEST.in
include-package-data = true

# ------------------------------------------------------------
# Package discovery
# ------------------------------------------------------------
# The equivalent of:
#   find_packages(exclude=("tests", "plot_tools", "docs"))
[tool.setuptools.packages.find]
where = ["."]           # top‑level directory
include = ["operadar*"] # include the main package (adjust if your package lives under src/)
exclude = ["tests*", "plot_tools*", "docs*"]   # the same exclusions you had
