#!/bin/bash
#SBATCH --job-name=operad
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=80
#SBATCH --exclusive
#SBATCH -o operad.eo%j
#SBATCH -e operad.eo%j
#SBATCH --no-requeue    ## pour ne pas C*tre remis en file d'attente si le job a C)tC) prC)emptC), mais C'a c'est toi qui vois
#SBATCH --time=07:00:00
#SBATCH -p normal256

ulimit -s unlimited
#ulimit -l unlimited   ## prC)vient les erreurs du type   RLIMIT_MEMLOCK too small
#ulimit -c 0

module purge
module load python/3.7.6nomkl


set -e
set -x
 
echo 'Lancement python3 operad.py'
# run program :

python3 operad.py


